plugins {
    id 'com.finpay.spring-conventions'
    id 'com.finpay.testing-conventions'
}

description = 'FinPay transfer-service.'

// Services are bootable applications.
bootJar {
    enabled = true
}
jar {
    enabled = true
}

dependencies {
    implementation libs.spring.boot.starter.web
    implementation libs.common.web
}
