plugins {
    id 'com.finpay.spring-conventions'
    id 'com.finpay.testing-conventions'
}

description = 'FinPay transfer-service.'

// Services are bootable applications.
bootJar {
    enabled = true
}
jar {
    enabled = true
}

dependencies {
    implementation libs.spring.boot.starter.web
    implementation libs.spring.boot.starter.validation
    implementation libs.spring.boot.starter.data.jpa
    implementation libs.common.web

    runtimeOnly libs.postgresql
    runtimeOnly libs.flyway.core
    runtimeOnly libs.flyway.database.postgresql

    testImplementation libs.spring.boot.starter.test
    testImplementation libs.testcontainers.postgresql
    testImplementation libs.common.test
}
