pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'transfer-service'

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven {
            name = 'GitHubPackages'
            url = uri('https://maven.pkg.github.com/finpay-lab/platform')
        }
    }
}

includeBuild 'build-logic'
