server:
  port: 8085
spring:
  application:
    name: transfer-service
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  otlp:
    tracing:
      endpoint: ${OTLP_ENDPOINT:http://otel-collector.finpay-infra.svc.cluster.local:4317}
    metrics:
      endpoint: ${OTLP_ENDPOINT:http://otel-collector.finpay-infra.svc.cluster.local:4317}
